#!/bin/sh
# A simple script to fix unresponsive trackpads on Lenovo IdeaPad 3 (15IIL05 Model)

sudo kernelstub -a "i8042.nopnp=1 pci=nocrs"

cat << Msg

ALL FINISHED! Reboot your laptop to enable the configuration.

Msg
